onOutput: ENH: Support optional fixed or percentage interval

diff --git a/bin/onOutput b/bin/onOutput
--- a/bin/onOutput
+++ b/bin/onOutput
@@ -28,9 +28,16 @@ HELPDESCRIPTION
     cat <<HELPTEXT
     --interval|-i INTERVAL[SUFFIX]
 			    Wait for INTERVAL seconds between executions of
-			    COMMANDS, even if there's continuous output. SUFFIX
-			    may be 's' for seconds (the default), 'm' for
+			    COMMANDS, even if there's continuous output.
+			    SUFFIX may be 's' for seconds (the default), 'm' for
 			    minutes, 'h' for hours or 'd' for days.
+			    ADJUSTMENT can change the original value after every
+			    iteration. It starts with either + or -, followed by
+			    TIMESPAN, optionally followed by either SUFFIX or %.
+			    For example, 10m+30s starts with 10 minutes and then
+			    increases that by 30 seconds on every iteration.
+			    10-5% starts with 10 seconds and then continually
+			    decreases that by 5 percent.
     --immediate|-I	    Directly execute COMMANDS for every (matching / not
 			    skipped) line; don't wait INTERVAL seconds.
     --line-interval|-l LINE-NUM
@@ -56,7 +63,76 @@ HELPDESCRIPTION
 HELPTEXT
 }
 
+timeToSeconds()
+{
+    case "$1" in
+	*([0-9]).+([0-9]))
+	    echo >&2 "ERROR: Floating point interval is not supported here."
+	    exit 2
+	    ;;
+	+([0-9])?(s))   time="${1%s}";;
+	+([0-9])m)	time=$((${1%m} * 60));;
+	+([0-9])h)	time=$((${1%h} * 3600));;
+	+([0-9])d)	time=$((${1%d} * 86400));;
+	*)		 >&2 'ERROR: Illegal interval: %s\n' "$1"; exit 2;;
+    esac
+    printf %s "$time"
+}
+timeWithAdjustmentToSeconds()
+{
+    local adjustment="${1##+([0-9.])?([smhd])}"
+    # Use this if no floating point is supported.
+    #local adjustment="${1##+([0-9])?([smhd])}"
+    local time="${1:0:$((${#1} - ${#adjustment}))}"
+    if [ -z "$time" ]; then
+	printf >&2 'ERROR: Empty interval: %s\n' "$time"; exit 2;
+    fi
+    case "$adjustment" in
+	'')			;;
+	[+-]+([0-9])?([smhd%]))	;;
+	*)  printf >&2 'ERROR: Illegal adjustment: %s\n' "$adjustment"; exit 2;;
+    esac
+    time="$(timeToSeconds "$time" "$2")" || exit $?
+    printf '%s\t%s\n' "$time" "$adjustment"
+}
+adjust()
+{
+    local var="${1?}"; shift
+    local adjustment="$1"; shift
+    eval "local value=\$$var"
+    local newValue
+    case "$adjustment" in
+	'')	    return;;
+	[+-]0?(%))  return;;
+	++([0-9]))  newValue="$((value + ${adjustment#+}))";;
+	-+([0-9]))  newValue="$((value - ${adjustment#-}))";;
+	[+-]+([0-9])%)
+		    # As Bash doesn't support floating point math yet, multiply
+		    # with 100, add the percentage change, and divide back and
+		    # round.
+		    # To avoid that the rounding truncates small changes and
+		    # therefore never lets the real value change, store the cent
+		    # value in a global variable, and re-use that instead.
+		    eval "local centValue=\$${var}CentValue"
+		    [ "$centValue" ] || centValue=$((value * 100))
+
+		    local change=$((${adjustment:1:-1} * value))
+		    [ "${adjustment:0:1}" = '+' ] && let centValue+=$change || let centValue-=$change
+		    newValue=$(((centValue + 50) / 100))
+
+		    eval "${var}CentValue=\$centValue"
+		    ;;
+	*)	    printf >&2 'ASSERT: Invalid adjustment: %s\n' "$adjustment"; exit 3;;
+    esac
+
+    [ $newValue -lt 0 ] && newValue=0
+    # Use this instead if no delay at all does not make sense.
+    #[ $newValue -le 0 ] && newValue=1
+    eval "$var=\$newValue"
+}
+
 interval=1
+intervalAdjustment=
 lineInterval=
 isNeedEval=
 typeset -a commands=()
@@ -69,16 +145,7 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-	--interval|-i)	shift
-			case "$1" in
-			    +([0-9])?(s))   interval="${1%s}";;
-			    +([0-9])m)	    interval=$((${1%m} * 60));;
-			    +([0-9])h)	    interval=$((${1%h} * 3600));;
-			    +([0-9])d)	    interval=$((${1%d} * 86400));;
-			    *)		    printf >&2 'ERROR: Illegal interval: %s\n' "$1"; exit 2;;
-			esac
-			shift
-			;;
+	--interval|-i)		shift; < <(timeWithAdjustmentToSeconds "$1") IFS=$'\t' read -r interval intervalAdjustment || exit 2; shift;;
 	--immediate|-I)		shift; interval=0;;
 	--line-interval|-l)	shift; lineInterval="${1:?}"; shift;;
 	--non-whitespace|-w)	shift; isNonWhitespace=t;;
@@ -172,7 +239,9 @@ do
     fi
 
     let lineCnt+=1
-    if [ $SECONDS -lt $interval ] && { [ ! "$lineInterval" ] || [ $lineCnt -lt $lineInterval ]; }; then
+    if [ $SECONDS -ge $interval ]; then
+	adjust interval "$intervalAdjustment"
+    elif [ ! "$lineInterval" ] || [ $lineCnt -lt $lineInterval ]; then
 	$process "${line}$EOL"
 	continue
     fi
