output{And,Or}{Printf,Prompt,Sleep}: Robustness: Do not accept unknown -* options

diff --git a/bin/outputAndPrintf b/bin/outputAndPrintf
--- a/bin/outputAndPrintf
+++ b/bin/outputAndPrintf
@@ -4,7 +4,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-w|--non-whitespace] [-o|--output FILESPEC|&N|-2|--stderr] [-a|--append] FORMAT [ARGUMENTS ...] [-?|-h|--help]'
+    printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-w|--non-whitespace] [-o|--output FILESPEC|&N|-2|--stderr] [-a|--append] [--] FORMAT [ARGUMENTS ...] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -59,6 +59,7 @@ do
 				;;
 	--append|-a)		shift; beforeArg=();;
 	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
diff --git a/bin/outputAndSleep b/bin/outputAndSleep
--- a/bin/outputAndSleep
+++ b/bin/outputAndSleep
@@ -8,7 +8,7 @@ one non-whitespace character), pause for NUMBER seconds.
 If no output is piped into the command, there's no delay, and the exit status is
 1.
 HELPTEXT
-    printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-w|--non-whitespace] NUMBER[SUFFIX] [...] [-?|-h|--help]'
+    printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-w|--non-whitespace] [--] NUMBER[SUFFIX] [...] [-?|-h|--help]'
 }
 
 typeset -a forwardedArgs=()
@@ -18,6 +18,7 @@ do
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 	--non-whitespace|-w)	forwardedArgs+=("$1"); shift;;
 	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
diff --git a/bin/outputOrPrintf b/bin/outputOrPrintf
--- a/bin/outputOrPrintf
+++ b/bin/outputOrPrintf
@@ -8,7 +8,7 @@ If there's no output (with -w|--non-whitespace: output that does not contain at
 least one non-whitespace character), printf FORMAT [ARGUMENTS ...] instead (with
 -2|--stderr: to standard error).
 HELPTEXT
-    printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-w|--non-whitespace] [-2|--stderr] FORMAT [ARGUMENTS ...] [-?|-h|--help]'
+    printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-w|--non-whitespace] [-2|--stderr] [--] FORMAT [ARGUMENTS ...] [-?|-h|--help]'
 }
 
 redir=
@@ -20,6 +20,7 @@ do
 	--non-whitespace|-w)	shift; tester=nonWhitespaceOutputOrError;;
 	--stderr|-2)		shift; redir='>&2';;
 	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
