outputAnd: CHG: Consistency: Rename --or to --or-command and add -O|--or-exec as well
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/outputAnd b/bin/outputAnd
--- a/bin/outputAnd
+++ b/bin/outputAnd
@@ -1,12 +1,13 @@
 #!/bin/bash
 
 : ${OUTPUTAND_COMMAND_JOINER=;}
+: ${OUTPUTAND_OR_END=;}
 
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-w|--non-whitespace] [-b|--before|-B|--before-command BEFORE-COMMANDLINE [...]] [-o|--or "NOOUT-COMMANDLINE" [...]] -c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]'
+    printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" "[-w|--non-whitespace] [-b|--before|-B|--before-command BEFORE-COMMANDLINE [...]] [-o|--or-command \"NOOUT-COMMANDLINE\" [-o ...] | -O|--or-exec NOOUT-SIMPLECOMMAND [...] ${OUTPUTAND_OR_END} [-O ...]] -c|--command \"COMMANDLINE\" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]"
 }
 printUsage()
 {
@@ -32,11 +33,16 @@ HELPDESCRIPTION
 			    Execute BEFORE-COMMANDLINEs before the output is
 			    printed. If these fail, COMMAND(s) after the output
 			    will not run.
-    --or|-o NOOUT-COMMANDLINE
+    --or-command|-o NOOUT-COMMANDLINE
 			    Execute NOOUT-COMMANDLINE if no (accepted) output
 			    has occurred. With this, you can handle both
 			    outcomes; i.e. either this or COMMAND(s) will be
 			    executed, never both.
+    --or-exec|-O NOOUT-SIMPLECOMMAND [...] ${OUTPUTAND_OR_END}
+			    Execute NOOUT-SIMPLECOMMAND if no (accepted) output
+			    has occurred; all following arguments are taken to
+			    be arguments to the NOOUT-SIMPLECOMMAND until an
+			    argument consisting of '${OUTPUTAND_OR_END}' is encountered.
 EXIT STATUS:
     0	Output occurred, and COMMAND(s) executed successfully.
     1	No output has been piped into the command (and NOOUT-COMMANDLINE
@@ -64,7 +70,22 @@ do
 	--non-whitespace|-w)	shift; isNonWhitespace=t; tester=nonWhitespaceOutputOrError;;
 	--before|-b)		shift; isBefore=t;;
 	--before-command|-B)	shift; beforeCommands+="${beforeCommands:+ $OUTPUTAND_COMMAND_JOINER }$1"; shift;;
-	--or|-o)		shift; noOutputCommands+="${noOutputCommands:+ $OUTPUTAND_COMMAND_JOINER }$1"; shift;;
+	--or-command|-o)	shift; noOutputCommands+="${noOutputCommands:+ $OUTPUTAND_COMMAND_JOINER }$1"; shift;;
+	--or-exec|-O)		shift
+				cmd=
+				while [ $# -gt 0 -a "$1" != "$OUTPUTAND_EXEC_END" ]
+				do
+				    printf -v quotedArg %q "$1"
+				    cmd+="${cmd:+ }${quotedArg}"
+				    shift
+				done
+				if [ $# -eq 0 ]; then
+				    echo "ERROR: --or-exec command must be concluded with '${OUTPUTAND_EXEC_END}'"; echo; printUsage "$0"
+				    exit 2
+				fi >&2
+				shift
+				noOutputCommands+="${noOutputCommands:+ $OUTPUTAND_COMMAND_JOINER }${cmd}"
+				;;
 	--command|-c)		shift; commands+="${commands:+ $OUTPUTAND_COMMAND_JOINER }$1"; shift;;
 	--)			shift; break;;
 	-*)			{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
