CHG: Don't apply --to DEFAULT-FILE(s) globally
Another --to DEFAULT-FILE adds to the list as long as no --[no-]match parameter has been encountered yet, and resets the list of default files once a --[no-]match parameter is encountered.
This way (at the cost of command-line argument position-dependency) we can support different sets of default files for different --[no-]match groups.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/segregatetee b/bin/segregatetee
--- a/bin/segregatetee
+++ b/bin/segregatetee
@@ -5,7 +5,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--to DEFAULT-FILE [--to ...]] (-m|--match PATTERN|-v|--no-match PATTERN [-a|--append] [--] [FILE ...]) ... [-f|--fallback [-a|--append] FALLBACK-FILE] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '([--to DEFAULT-FILE [--to ...]] -m|--match PATTERN|-v|--no-match PATTERN [-a|--append] [--] [FILE ...]) ... [-f|--fallback [-a|--append] FALLBACK-FILE] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -26,11 +26,15 @@ HELPDESCRIPTION
     echo
     printShortUsage "$1"
     cat <<HELPTEXT
-    --to DEFAULT-FILE	    Write to DEFAULT-FILE if no FILE(s) are given
-			    (instead of falling back to standard output). This
-			    allows to specify a FILE once for multiple PATTERNs
-			    without repeating it (which is important when using
-			    a single process substitution).
+    --to DEFAULT-FILE	    Write to DEFAULT-FILE if no FILE(s) are given to a
+			    following --[no-]match parameter (instead of falling
+			    back to standard output). This allows to specify a
+			    FILE once for multiple PATTERNs without repeating it
+			    (which is important when using a single process
+			    substitution). Another --to DEFAULT-FILE adds to the
+			    list as long as no --[no-]match parameter has been
+			    encountered yet, and resets the list of default
+			    files once a --[no-]match parameter is encountered.
     --match|-m PATTERN	    Only consider lines that match PATTERN when writing
 			    to the following FILE(s). If no FILE(s) are given,
 			    write to standard output / FALLBACK-FILE.
@@ -52,21 +56,29 @@ HELPTEXT
 }
 
 typeset -a filespecs=()
-addFile()
+addFiles()
 {
     local varname="${1:?}"; shift
-    local file="${1:?}"; shift
-    local i; for ((i = 0; i < ${#filespecs[@]}; i++))
+    local file; for file
     do
-	if [ "$file" = "${filespecs[$i]}" ]; then
-	    eval "${varname}+=\"\$i \""
-	    return
-	fi
+	local i; for ((i = 0; i < ${#filespecs[@]}; i++))
+	do
+	    if [ "$file" = "${filespecs[$i]}" ]; then
+		eval "${varname}+=\"\$i \""
+		return
+	    fi
+	done
+	eval "${varname}+=\"\${#filespecs[@]} \""
+	filespecs+=("$file")
     done
-    eval "${varname}+=\"\${#filespecs[@]} \""
-    filespecs+=("$file")
+}
+handleDefaultFiles()
+{
+    [ -n "$lastPattern" ] && [ -z "${matchFileIndices["$lastPattern"]}" ] || return
+    addFiles 'matchFileIndices["$lastPattern"]' "${defaultFiles[@]}"
 }
 
+isDefaultFilesUsed=
 lastPattern=
 typeset -a matchPatterns=()
 typeset -A matchIsExclude=()
@@ -74,25 +86,37 @@ typeset -A matchIsAppend=()
 typeset -A matchFileIndices=()
 fallbackIsAppend=
 fallbackFileIndices=
-defaultFileIndices=
+typeset -a defaultFiles=()
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 
-	--match=*)	lastPattern="${1#--match=}"; shift; matchPatterns+=("$lastPattern"); matchIsExclude["$lastPattern"]=;;
-	--match|-m)	shift; lastPattern="${1:?}"; shift; matchPatterns+=("$lastPattern"); matchIsExclude["$lastPattern"]=;;
-	--no-match=*)	lastPattern="${1#--no-match=}"; shift; matchPatterns+=("$lastPattern"); matchIsExclude["$lastPattern"]=t;;
-	--no-match|-v)	shift; lastPattern="${1:?}"; shift; matchPatterns+=("$lastPattern"); matchIsExclude["$lastPattern"]=t;;
+	--match=*)	handleDefaultFiles; lastPattern="${1#--match=}"; shift; matchPatterns+=("$lastPattern"); matchIsExclude["$lastPattern"]=; isDefaultFilesUsed=t;;
+	--match|-m)	shift; handleDefaultFiles; lastPattern="${1:?}"; shift; matchPatterns+=("$lastPattern"); matchIsExclude["$lastPattern"]=; isDefaultFilesUsed=t;;
+	--no-match=*)	handleDefaultFiles; lastPattern="${1#--no-match=}"; shift; matchPatterns+=("$lastPattern"); matchIsExclude["$lastPattern"]=t; isDefaultFilesUsed=t;;
+	--no-match|-v)	shift; handleDefaultFiles; lastPattern="${1:?}"; shift; matchPatterns+=("$lastPattern"); matchIsExclude["$lastPattern"]=t; isDefaultFilesUsed=t;;
 
 	--fallback|-f)	shift
 			if [[ "$1" = @(--append|-a) ]]; then
 			    shift
 			    fallbackIsAppend=t
 			fi
-			addFile fallbackFileIndices "${1:?}"
-			shift;;
-	--to)		shift; addFile defaultFileIndices "${1:?}"; shift;;
+			addFiles fallbackFileIndices "${1:?}"
+			shift
+			lastPattern=''
+			;;
+	--to)		shift
+			handleDefaultFiles
+			if [ "$isDefaultFilesUsed" ]; then
+			    isDefaultFilesUsed=
+			    defaultFiles=("${1:?}")
+			else
+			    defaultFiles+=("${1:?}")
+			fi
+			shift
+			lastPattern=''
+			;;
 	--append|-a)	shift
 			if [ -z "$lastPattern" ]; then
 			    echo 'ERROR: --append must follow a --match or --no-match parameter.'
@@ -110,16 +134,17 @@ do
 	-|-[^-]*|--?*)	{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	--)		shift;&
 	*)		if [ -z "$lastPattern" ]; then
-			    echo 'ERROR: FILE(s) must follow a --match or --no-match parameter.'
+			    printf 'ERROR: FILE(s) must follow a --match or --no-match parameter: %s\n' "$1"
 			    echo
 			    printUsage "$0"
 			    exit 2
 			fi >&2
-			addFile 'matchFileIndices["$lastPattern"]' "${1:?}"
+			addFiles 'matchFileIndices["$lastPattern"]' "${1:?}"
 			shift
 			;;
     esac
 done
+handleDefaultFiles
 if [ ${#matchPatterns[@]} -eq 0 ]; then
     echo 'ERROR: No --match or --no-match passed.'
     echo
@@ -134,12 +159,8 @@ write()
     local isAppend="${1?}"; shift
 
     if [ -z "$fileIndices" ]; then
-	if [ -n "$defaultFileIndices" ]; then
-	    fileIndices="$defaultFileIndices"
-	else
-	    printf %s "$contents"
-	    return
-	fi
+	printf %s "$contents"
+	return
     fi
 
     local i; for i in $fileIndices
@@ -178,6 +199,6 @@ do
 	    break
 	fi
     done
-    [ "$hasMatch" ] || defaultFileIndices='' write "${line}$EOL" "$fallbackFileIndices" t
+    [ "$hasMatch" ] || write "${line}$EOL" "$fallbackFileIndices" t
 done
 exit $status
