ENH: Allow ignoring of incomplete lines

diff --git a/bin/singleLineOrSuppressAndError b/bin/singleLineOrSuppressAndError
--- a/bin/singleLineOrSuppressAndError
+++ b/bin/singleLineOrSuppressAndError
@@ -4,7 +4,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-v|--verbose|--no-input-error MSG --multiple-lines-error MSG] [--] FILE [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--ignore-incomplete] [-v|--verbose|--no-input-error MSG --multiple-lines-error MSG] [--] FILE [...] [-?|-h|--help]'
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[...]'
 }
 printUsage()
@@ -26,6 +26,10 @@ HELPDESCRIPTION
     printShortUsage "$1"
     echo
     cat <<HELPTEXT
+    --ignore-incomplete	Don't accept a single line without a trailing newline.
+			Accept one line followed by one newline and additional
+			characters (but don't output anything after the
+			newline).
     -v|--verbose	Print an error message complaining about no / too many
 			lines.
     --no-input-error MSG
@@ -42,12 +46,15 @@ EXIT STATUS:
     99	No input has been encountered.
 HELPTEXT
 }
+isAcceptIncompleteLine=t
 noInputErrorMessage=
 multipleLinesErrorMessage=
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--ignore-incomplete)
+			shift; isAcceptIncompleteLine=;;
 	--verbose|-v)	shift
 			noInputErrorMessage='ERROR: No input.'
 			multipleLinesErrorMessage='ERROR: More than one line.'
@@ -63,8 +70,8 @@ do
 done
 
 isEOL=t
-if IFS=$'\n' read -r line || { isEOL=; [ -n "$line" ]; }; then
-    if IFS=$'\n' read -r ignoredSecondLine; then
+if IFS=$'\n' read -r line || { isEOL=; [ "$isAcceptIncompleteLine" ] && [ -n "$line" ]; }; then
+    if IFS=$'\n' read -r secondLine || { [ "$isAcceptIncompleteLine" ] && [ -n "$secondLine" ]; }; then
 	[ -z "$multipleLinesErrorMessage" ] || printf >&2 '%s\n' "$multipleLinesErrorMessage"
 	cat >/dev/null
 	exit 1
